### ISSUE TITLE
FinTrinity stops when a qcma copy is in progress

### ISSUE THREAD

**Issue by theowhy** [bamhm182/FinTrinity#13]
When a copy is in progress a _TEMP folder is created by QCMA and this breaks the the line findall(r"([A-Z]{4}[0-9]{5})$", folder)[0] as the regexp does not catch anything.

Should those folders be skipped or a message requesting user to wait until copy is over would be better ?

**Comment by bamhm182** [comment]
That's a good question. The easiest method would just be to skip them, but then the user might run into an issue where they aren't seeing their game because it is transferring and they might not understand why. I'll put in a check with a message.

Thanks for finding this! It also let me know of a bug that would cause that line to crash the program since there is no 0 index of a folder if it existed, but didn't match that regex. Fixed that while I was at it.

**Comment by bamhm182** [comment]
Problem resolved in release v0.5. Closing.
